### PR TITLE
Update to scraper.

### PR DESCRIPTION
**Pull request by muzza1976**
Minor updates to scraper to get working again due to changes to web page.

### CODE REVIEW

**Comment by muzza1976** [comment]
Scraper is currently running successfully in morph.io. https://morph.io/muzza1976/greater_geelong

**Comment by muzza1976** [comment]
Updated the recently committed changes to get the open permit applications opposed to the finished.

**Comment by jamezpolley** [comment]
This should fix #5 

@mlandauer Could you comment on why the scraper currently looks only at the FINISHED table?

 I'm thinking that we probably want to scrape both tables - so that we can get updates to get the final status of applications from the FINISHED table, as well as the CURRENT table for things that are just now going on advertisement. Does that make sense?

**Comment by mlandauer** [comment]
Thanks @muzza1976 for the fix! I have no idea how I managed to update things to scrape the wrong table on that page. Thanks so much for fixing it! This fixed #5.

**Pull request merged**
